### ISSUE TITLE
Stop-AvdSessionHost Single Session Host issue.

### ISSUE THREAD

**Issue by WiseK** [srozemuller/AzAvd#138]
This is not working correctly for a single sessionhost. 
Stop-AvdSessionHost -HostpoolName AVD-Testpool -ResourceGroupName RG -Name AVDW11 
HINT: use -Force to skip this message.
Are you sure you want to run Stop-AvdSessionHost to all session hosts? [y/n]:
AVD-Testpool/AVDW11-12 stopped
AVD-Testpool/AVDW11-13 stopped
AVD-Testpool/AVDW11-14 stopped
AVD-Testpool/AVDW11-15 stopped
AVD-Testpool/AVDW11-16 stopped

If you choose No it closes Powershell. 
If you use -Force it appears to try to stop all hosts.
Documentation has -Name and -SessionHostName specified.  -Name works.

**Comment by srozemuller** [comment]
Hi @WiseK did you try the beta release from this repository? You can find it under releases.

**Comment by srozemuller** [comment]
Hi @WiseK could you please check release : https://github.com/srozemuller/AzAvd/releases/tag/3.0.0-beta.264
