### ISSUE TITLE
Error - Please connect to AVD first using the Connect-Avd command

### ISSUE THREAD

**Issue by WiseK** [srozemuller/AzAvd#167]
Getting an error with multiple versions of AZ.AVD.
    Throw "Please connect to AVD first using the Connect-Avd comm …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Please connect to AVD first using the Connect-Avd command

The script connects first, then install and import. I get the same error with 2.5.1, 3.0.0. and the latest. Last month I didn't have this issue with the same exact script.     
   		Connect-AZAccount
                Install-Module -Name Az.AVD -RequiredVersion 2.5.1 -Force
                Import-Module Az.AVD
                $HostPoolName =

**Comment by WiseK** [comment]
Running a simple command to get-avdhostpool 
Connect-AzAccount
get-avdhostpool -HostPoolName $hostpoolname -ResourceGroupName $resourcegroupname
PowerShell\Modules\Az.AVD\3.0.0\Private\global-functions.ps1:32
Line |
  32 |          Throw "Please connect to AVD first using the Connect-Avd comm …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Please connect to AVD first using the Connect-Avd command

**Comment by srozemuller** [comment]
Hi @WiseK please use the command Connect-Avd first. https://github.com/srozemuller/AzAvd/blob/main/README.md#connect-to-avd

The Connect-AzAccount is not needed anymore. That makes the Az.Avd module complete independent.

**Comment by WiseK** [comment]
@srozemuller Thanks that helps. I didn't realize there was a change until several of my scheduled actions started failing. 

With Git Action workflows, you are already logged in with an SP typically. 
steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{secrets.}} #This would typically be the SP

Then we would have to log in again to Connect-AVD. Are there any ways to eliminate this step or it's just going to be required to keep the module independent?
 $subscriptionid = "SUBID"
            $Tenantid = '${{secrets}}'
            $clientID = '${{secrets.}}'
            $ClientSecret = '${{secrets.}}'
            Connect-Avd -ClientID $clientID -ClientSecret $ClientSecret -TenantID $Tenantid -SubscriptionId $SubscriptionId

**Comment by srozemuller** [comment]
Good point!  I will add a service principal login to the module.

**Comment by srozemuller** [comment]
@WiseK I updated the module. The Connect-Avd command accepts also an access token from earlier steps. Just provide the access token to the command and you are logged in.
