### ISSUE TITLE
Get-AvdImageVersionStatus -  LatestVersion shows False for everything, and the wrong version is listed.

### ISSUE THREAD

**Issue by WiseK** [srozemuller/AzAvd#175]
Running the Get-AVDIMAGEVERSIONStatus is showing an old version as latest. I tested on a couple host pools and also verified the images were latest in the compute gallery however everything is marked false for isLatestVersion.

$SessionHosts = Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $ResourceGroupName -NotLatest
write-output $sessionhosts

The Latest Version should have been listed as 0.0.11 and True the first vm and the second VM would be False but Latest version is showing 0.0.9.
currentImageVersion : 0.0.11
latestVersion       : 0.0.9
isLatestVersion     : False

currentImageVersion : 0.0.10
latestVersion       : 0.0.9
isLatestVersion     : False

![image](https://github.com/srozemuller/AzAvd/assets/36459197/b87455c9-b7eb-46bd-82ef-c58bd45d1625)

**Comment by WiseK** [comment]
It seems to be an issue with sorting and comparing the versions numerically.

**Comment by srozemuller** [comment]
Thank you @WiseK 
Will take a look into it.

**Comment by srozemuller** [comment]
Hi @WiseK I have tested it with the latest module version and works as expected.
