### ISSUE TITLE
Get-AvdSessionHost does not return more than 200 session hosts at a time

### ISSUE THREAD

**Issue by daveongit** [srozemuller/AzAvd#46]
On host pools with more 200 session hosts, I cannot seem to return more than the first 200 hosts when using the following code and the latest version of the Az.Avd module (at time of writing, it is 2.2.0):

$hpName = 'HostPoolNameHere'
$rgName = (Get-AzResource -Name $hpName).ResourceGroupName
Get-AvdSessionHost -HostpoolName $hpName -ResourceGroupName $rgName

I can run Get-AvdSessionHost on specific hosts above #200 with success, but never all in the same command.  Is this a limitation of your module or perhaps something else?  Have you run into this problem?

P.S. Thanks for creating this module!  I don't know if there is a better or preferred way to contact you outside of a public Twitter mention, so I hope this is seen and an acceptable place to ask questions like this.

**Comment by srozemuller** [comment]
HI @daveongit I've created a beta release with some updates around session host management. Are you able to download the release and import the module 

https://github.com/srozemuller/AzAvd/releases/tag/v2.3.3-beta.11
