### ISSUE TITLE
New-AvdAutoScaleRole.ps1 Service Rename WVD => AVD?

### ISSUE THREAD

**Issue by zimbo86** [srozemuller/AzAvd#53]
This function terminated with an error today.
Shouldnt line 93 be changed from
```$servicePrincipalURL = $Script:GraphApiUrl + "/" +$script:GraphApiVersion + "/servicePrincipals?`$filter=displayName eq 'Windows Virtual Desktop'"```
to 
```$servicePrincipalURL = $Script:GraphApiUrl + "/" +$script:GraphApiVersion + "/servicePrincipals?`$filter=displayName eq 'Azure Virtual Desktop'"```
as there is no "Windows Virtual Desktop" Service anymore?
![image](https://user-images.githubusercontent.com/69269000/181234446-c7a12c26-c01c-46a0-b7b3-e2f296a13257.png)

Error:
```
Invoke-RestMethod : {"error":{"code":"InvalidRequestContent","message":"The content of your request was not valid, and the original object could not be deserialized. Exception message: 'Required property 'principalId' expects a value but got null. Path 'properties', line 5, position 20.'"}}
```

**Comment by zimbo86** [comment]
Just the -assign switch does not work.
`New-AzRoleAssignment -RoleDefinitionName "Desktop Virtualization Autoscale" -ResourceGroupName $ResourceGroupName  -ApplicationId $(Get-AzADServicePrincipal -DisplayName "Azure Virtual Desktop").AppID
` 
works like a charm.

**Comment by srozemuller** [comment]
Hi @zimbo86  thank you for using my module and really appreciate your feedback.
About the first one. Currently, only the app display name is changed. The underlying display name is still Windows Virtual Desktop. I've tested at my own tenant and still got results. 

Will take a look at the assign part.
