### ISSUE TITLE
Update-AvdSessionhostDrainMode

### ISSUE THREAD

**Issue by pelu28** [srozemuller/AzAvd#54]
Using it with parameters or with Get-AvdImageVersionStatus -HostpoolName xxxxxx -ResourceGroupName xxxxxx -NotLatest | foreach {Update-AvdSessionhostDrainMode -HostpoolName $_.HostpoolName -ResourceGroupName xxxxx -SessionHostName $_.SessionHostName -AllowNewSession $false} gives error like below.
```

Update-AvdSessionHost: C:\Program Files\WindowsPowerShell\Modules\Az.Avd\2.3.2\Public\Update-AvdSessionhostDrainMode.ps1:69
Line |
  69 |              Update-AvdSessionhost @Parameters
     |                                    ~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'Name'.
```

Same problems also with other module commands if using your blog example
```

Get-AvdImageVersionStatus -HostpoolName xxxxxxxx -ResourceGroupName xxxxxxxxx -NotLatest | 
foreach {
    $sessionHostInfo = @{
        HostpoolName = $_.HostpoolName
        ResourceGroupName = "xxxxxxx" 
        SessionHostName = $_.SessionHostName
    }
    
    $sessionHost = Get-AvdSessionHostResources @sessionHostInfo
    Remove-AzResource -ResourceId $sessionHost.Id -Force
    Remove-AzResource -ResourceId $sessionHost.StorageProfile.OsDisk.ManagedDisk.id -Force
    Remove-AzResource -ResourceId (Get-AvdNetworkInfo @sessionHostInfo).nicId -Force
}
```

```
Get-AvdSessionHostResources:
Line |
   9 |      $sessionHost = Get-AvdSessionHostResources @sessionHostInfo
     |                                                 ~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'SessionHostName'.
Remove-AzResource:
Line |
  10 |      Remove-AzResource -ResourceId $sessionHost.Id -Force
     |                                    ~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
Remove-AzResource:
Line |
  11 |  …  -ResourceId $sessionHost.StorageProfile.OsDisk.ManagedDisk.id -Force
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
Exception: C:\Program Files\WindowsPowerShell\Modules\Az.Avd\2.3.2\Public\Get-AvdNetworkInfo.ps1:60
Line |
  60 |              Throw "No sessionhosts found, $_"
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No sessionhosts found, A parameter cannot be found that matches parameter name 'SessionHostName'.
```

Using latest modules and tried with powershell 5 and 7 versions.

**Comment by srozemuller** [comment]
Thank you @pelu28 for using the module and your feedback. Will take this with me in the next release.

**Comment by srozemuller** [comment]
@pelu28 I updated the code in a beta version and updated my post: https://www.rozemuller.com/how-to-deal-with-avd-session-hosts-version-management/

https://github.com/srozemuller/AzAvd/releases/tag/v2.3.3-beta.13

**Comment by pelu28** [comment]
@srozemuller i dont know what im doing wrong but if -SessionHostName in any command is used i get 

`No sessionhosts found, A parameter cannot be found that matches parameter name 'SessionHostName'.
At C:\Users\peluo1\Documents\WindowsPowerShell\Modules\2.4.3\Az.Avd\Public\Get-AvdNetworkInfo.ps1:60 char:13
+             Throw "No sessionhosts found, $_"`

`Line |
  60 |              Throw "No sessionhosts found, $_"
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No sessionhosts found, A parameter cannot be found that matches parameter name 'SessionHostName'.`

tried to give all parameters manually with flag -SessionHostName "hostpool/sessionhost.daa.daa" or just the name etc.

example now running your blog example to remove sessionhosts first two lines go fine but when it tries to list/find NIC i will get above error. If i run get-avdnetworkinfo with hostpool and rg it works but with sessionhostname does not.

**Comment by srozemuller** [comment]
> @srozemuller i dont know what im doing wrong but if -SessionHostName in any command is used i get
> 
> `No sessionhosts found, A parameter cannot be found that matches parameter name 'SessionHostName'. At C:\Users\peluo1\Documents\WindowsPowerShell\Modules\2.4.3\Az.Avd\Public\Get-AvdNetworkInfo.ps1:60 char:13
> 
> * ```
>           Throw "No sessionhosts found, $_"`
>   ```
> 
> `Line | 60 | Throw "No sessionhosts found, $_" | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | No sessionhosts found, A parameter cannot be found that matches parameter name 'SessionHostName'.`
> 
> tried to give all parameters manually with flag -SessionHostName "hostpool/sessionhost.daa.daa" or just the name etc.
> 
> example now running your blog example to remove sessionhosts first two lines go fine but when it tries to list/find NIC i will get above error. If i run get-avdnetworkinfo with hostpool and rg it works but with sessionhostname does not.

@pelu28 thank you so much for testing. I noticed there was a bug in the network info part.
Could you please check the new release
https://github.com/srozemuller/AzAvd/releases/tag/v2.4.3-beta.16
