### ISSUE TITLE
Function Get-AvdSessionHost  when using ID parameter reports that an incorrect api version is defined

### ISSUE THREAD

**Issue by ShocOne** [srozemuller/AzAvd#58]
Hi there

Error message below when trying to run the function. 

Line |
   8 |  Get-AvdSessionHost  -Id '/subscriptions/664e145d-... …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No sessionhost results in ,
     | {"error":{"code":"NoRegisteredProviderFound","message":"No registered
     | resource provider found for location 'uksouth' and API version
     | '2021-07-12' for type 'virtualMachines'. The supported api-versions are
     | '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview,
     | 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01,
     | 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-12-01, 2021-03-01,
     | 2021-04-01, 2021-07-01, 2021-11-01, 2022-03-01, 2022-08-01, 2022-11-01'.
     | The supported locations are 'eastus, eastus2, westus, centralus,
     | northcentralus, southcentralus, northeurope, westeurope, eastasia,
     | southeastasia, japaneast, japanwest, australiaeast, australiasoutheast,
     | australiacentral, brazilsouth, southindia, centralindia, westindia,
     | canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest,
     | koreacentral, koreasouth, francecentral, southafricanorth, uaenorth,
     | switzerlandnorth, germanywestcentral, norwayeast, jioindiawest, westus3,
     | swedencentral, qatarcentral'."}}

The function when reviewing the Get-AvdSessionHost.ps1 reports the api version as "?api-version=2021-07-12"

Thanks

Dafydd

**Comment by srozemuller** [comment]
> Hi there
> 
> Error message below when trying to run the function.
> 
> Line | 8 | Get-AvdSessionHost -Id '/subscriptions/664e145d-... … | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | No sessionhost results in , | {"error":{"code":"NoRegisteredProviderFound","message":"No registered | resource provider found for location 'uksouth' and API version | '2021-07-12' for type 'virtualMachines'. The supported api-versions are | '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, | 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, | 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-12-01, 2021-03-01, | 2021-04-01, 2021-07-01, 2021-11-01, 2022-03-01, 2022-08-01, 2022-11-01'. | The supported locations are 'eastus, eastus2, westus, centralus, | northcentralus, southcentralus, northeurope, westeurope, eastasia, | southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, | australiacentral, brazilsouth, southindia, centralindia, westindia, | canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, | koreacentral, koreasouth, francecentral, southafricanorth, uaenorth, | switzerlandnorth, germanywestcentral, norwayeast, jioindiawest, westus3, | swedencentral, qatarcentral'."}}
> 
> The function when reviewing the Get-AvdSessionHost.ps1 reports the api version as "?api-version=2021-07-12"
> 
> Thanks
> 
> Dafydd

Hi @dafyyd , I think you are using the wrong resource ID.. You should use the session host resource ID not the virtual machine resource ID. 

Sander
