### ISSUE TITLE
New-AvdSessionHost Freeze

### ISSUE THREAD

**Issue by h-sadeghpour** [srozemuller/AzAvd#92]
Hi,

When I trigger the New-AvdSessionHost with all the necessary parameters, it does nothing and freezes for hours - in the previous version in 2.5.1 also it's returning an error to the -Domain parameter and says:

Line |
 311 |  …             Invoke-RestMethod -Method PUT -Uri $domainJoinUrl -Header …
     |                                                   ~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null
     | or empty, and then try the command again.

Any support on that?

**Comment by srozemuller** [comment]
Hi @h-sadeghpour let me have a check on that. Thank you for your comment

**Comment by h-sadeghpour** [comment]
With version 3.0.0 Beta this is where it freezes - thought might be helpful - But with version 2.5.1 the "Uri" error is keep coming as mentioned in the main post.

<img width="409" alt="image" src="https://github.com/srozemuller/AzAvd/assets/49187548/e2329907-661b-43b2-af44-aac911cfa0cf">

**Comment by srozemuller** [comment]
Hi @h-sadeghpour  are you able to test release https://github.com/srozemuller/AzAvd/releases/tag/3.0.0-beta.8

**Comment by h-sadeghpour** [comment]
Hi,

I have tested it, it's the same issue.

Kind regards,
Hamid Sadeghpour Saleh
<http://hamidsadeghpour.net/>
Microsoft Solutions Consultant
MVP: Microsoft Azure | Cloud and Datacenter Management

https://hamidsadeghpour.net<http://hamidsadeghpour.net/> | ***@***.***

[cid:037632c5-49a8-4ab4-aa9f-edcba5b8decf][cid:0a570dda-e149-4822-8acf-5374ee59b289]
________________________________

**Comment by srozemuller** [comment]
Hi @h-sadeghpour a lot has been changed on the session host deployment. I've tested many time with no issues anymore. Are you able to test 3.0.0 from the PSGallery
